In [2]:
#Importamos Librerias
import pandas as pd
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [3]:
#Cargamos archivo
df= pd.read_csv('RiodeJaneiro.csv') 

#Seleccionamos solo las columnas que utilizaremos para este an√°lisis y crearemos un nuevo dataframe
df2 = df.loc[:, ['source','name', 'host_id','host_response_time','host_response_rate','host_acceptance_rate',
'host_is_superhost','host_listings_count','host_total_listings_count','host_identity_verified', 'neighbourhood',
'neighbourhood_cleansed','latitude','longitude','property_type','room_type','accommodates', 'bathrooms_text', 'bedrooms',
'beds','Ame1', 'Ame2','Ame3','Ame4','Ame5', 'price', 'minimum_nights', 'maximum_nights', 'number_of_reviews', 'number_of_reviews_lastyear', 
'number_of_reviews_last30', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin',
'review_scores_communication', 'review_scores_location', 'review_scores_value', 'instant_bookable', 'calculated_host_listings_count', 
'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms']]

df3=df2.drop([15110], axis=0)

/var/folders/s5/9tn200911wjfzyc3b8q58s900000gn/T/ipykernel_81958/2467423950.py:2: DtypeWarning: Columns (0,2,9,47,62,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('RiodeJaneiro.csv')

In [4]:

#Convertimos algunas columnas de object a float64
df3['review_scores_rating'] = df3['review_scores_rating'].astype(float, errors = 'raise')
df3['review_scores_accuracy'] = df3['review_scores_accuracy'].astype(float, errors = 'raise')
df3['review_scores_cleanliness'] = df3['review_scores_cleanliness'].astype(float, errors = 'raise')
df3['review_scores_checkin'] = df3['review_scores_checkin'].astype(float, errors = 'raise')
df3['review_scores_communication'] = df3['review_scores_communication'].astype(float, errors = 'raise')

df3.dtypes

source                                           object
name                                             object
host_id                                          object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                             object
host_is_superhost                                object
host_listings_count                             float64
host_total_listings_count                       float64
host_identity_verified                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                    float64
bathrooms_text                                   object
bedrooms                                        float64
beds                                            float64
Ame1                                             object
Ame2                                             object
Ame3                                             object
Ame4                                             object
Ame5                                             object
price                                           float64
minimum_nights                                  float64
maximum_nights                                  float64
number_of_reviews                               float64
number_of_reviews_lastyear                      float64
number_of_reviews_last30                        float64
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
instant_bookable                                 object
calculated_host_listings_count                  float64
calculated_host_listings_count_entire_homes     float64
calculated_host_listings_count_private_rooms    float64
calculated_host_listings_count_shared_rooms     float64
dtype: object

In [5]:
### Cambiamos algunas variables de str a booleanos
#host_is_superhost
#host_identity_verified
#instant_bookable

df3['host_is_superhost'] = df3['host_is_superhost'].replace("f", "0")
df3['host_is_superhost'] = df3['host_is_superhost'].replace("t", "1")

df3['host_identity_verified'] = df3['host_identity_verified'].replace("f", "0")
df3['host_identity_verified'] = df3['host_identity_verified'].replace("t", "1")

df3['instant_bookable'] = df3['instant_bookable'].replace("f", "0")
df3['instant_bookable'] = df3['instant_bookable'].replace("t", "1")
df3

,source,name,host_id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
0,city scrape,Suntuoso apartamento em Copacabana posto 6,431412286,within an hour,100%,100%,0,10.0,10.0,1,...,NaN,NaN,NaN,NaN,NaN,1,10.0,8.0,2.0,0.0
1,city scrape,Ipanema Vieira Souto - Linda Vista,40650139,a few days or more,13%,100%,0,6.0,6.0,1,...,NaN,NaN,NaN,NaN,NaN,1,5.0,5.0,0.0,0.0
2,city scrape,Casa compartilhada,87749071,NaN,NaN,NaN,0,1.0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,0.0,0.0
3,city scrape,Aluguel de Lancha no Rio de Janeiro,97164727,within an hour,100%,100%,0,4.0,4.0,1,...,5.0,5.0,5.0,5.0,5.0,0,2.0,2.0,0.0,0.0
4,city scrape,Uma grande fam√≠lia,249666532,NaN,NaN,NaN,0,1.0,1.0,0,...,NaN,NaN,NaN,NaN,NaN,1,1.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26369,city scrape,Quarto mobiliado aconchegante em Copacabana/RJ,285054840,within an hour,100%,100%,0,1.0,1.0,1,...,NaN,NaN,NaN,NaN,NaN,0,1.0,0.0,1.0,0.0
26370,city scrape,Small 1 bed aprt with panoramic roof top access,444164486,within an hour,100%,100%,1,4.0,4.0,0,...,NaN,NaN,NaN,NaN,NaN,1,4.0,2.0,2.0,0.0
26371,city scrape,Apartamento RJ perto da praia,335934644,within a day,50%,6%,0,2.0,2.0,1,...,NaN,NaN,NaN,NaN,NaN,0,2.0,2.0,0.0,0.0
26372,city scrape,Loft encantador de frente pra praia - Copacabana,434256437,within a few hours,98%,73%,0,3.0,3.0,0,...,NaN,NaN,NaN,NaN,NaN,0,3.0,2.0,1.0,0.0
26373,city scrape,Casa da Floresta,5347577,within an hour,100%,100%,0,2.0,3.0,1,...,NaN,NaN,NaN,NaN,NaN,1,2.0,1.0,1.0,0.0

**Sustituci√≥n de Nulos**

In [6]:
#Detectamos valores nulos
valores_nulos = df3.isnull().sum()
valores_nulos
#df3.isnull().sum().sum()

source                                              5
name                                               24
host_id                                             6
host_response_time                               3515
host_response_rate                               3515
host_acceptance_rate                             3535
host_is_superhost                                  14
host_listings_count                                12
host_total_listings_count                          12
host_identity_verified                             13
neighbourhood                                   12478
neighbourhood_cleansed                              7
latitude                                            7
longitude                                           7
property_type                                       7
room_type                                           7
accommodates                                        7
bathrooms_text                                     58
bedrooms                                         1319
beds                                              244
Ame1                                               27
Ame2                                              284
Ame3                                              384
Ame4                                              535
Ame5                                              818
price                                               8
minimum_nights                                      8
maximum_nights                                      8
number_of_reviews                                   8
number_of_reviews_lastyear                          8
number_of_reviews_last30                            8
review_scores_rating                             7030
review_scores_accuracy                           7236
review_scores_cleanliness                        7236
review_scores_checkin                            7236
review_scores_communication                      7236
review_scores_location                           7237
review_scores_value                              7236
instant_bookable                                    8
calculated_host_listings_count                      8
calculated_host_listings_count_entire_homes         8
calculated_host_listings_count_private_rooms        8
calculated_host_listings_count_shared_rooms         8
dtype: int64

In [7]:
#Primero sustituimos todos los valores nulos de lascolumnas de tipo "float64"

#Sustituir valores nulos con la mediana

median_host_listings_count=df3['host_listings_count'].median() 
df3['host_listings_count'].fillna(value=median_host_listings_count, inplace=True) 
median_host_total_listings_count=df3['host_total_listings_count'].median() 
df3['host_total_listings_count'].fillna(value=median_host_total_listings_count, inplace=True) 
median_accommodates=df3['accommodates'].median() 
df3['accommodates'].fillna(value=median_accommodates, inplace=True) 
median_bedrooms=df3['bedrooms'].median() 
df3['bedrooms'].fillna(value=median_bedrooms, inplace=True) 
median_beds=df3['beds'].median() 
df3['beds'].fillna(value=median_beds, inplace=True) 
median_minimum_nights=df3['minimum_nights'].median() 
df3['minimum_nights'].fillna(value=median_minimum_nights, inplace=True) 
median_maximum_nights=df3['maximum_nights'].median() 
df3['maximum_nights'].fillna(value=median_maximum_nights, inplace=True) 
median_number_of_reviews=df3['number_of_reviews'].median() 
df3['number_of_reviews'].fillna(value=median_number_of_reviews, inplace=True) 
median_number_of_reviews_lastyear=df3['number_of_reviews_lastyear'].median() 
df3['number_of_reviews_lastyear'].fillna(value=median_number_of_reviews_lastyear, inplace=True) 
median_number_of_reviews_last30=df3['number_of_reviews_last30'].median() 
df3['number_of_reviews_last30'].fillna(value=median_number_of_reviews_last30, inplace=True) 

#Sustituir valores nulos con la media

mean_price=df3['price'].mean() 
df3['price'].fillna(value=mean_price,inplace=True) 
mean_latitude=df3['latitude'].mean() 
df3['latitude'].fillna(value=mean_latitude,inplace=True) 
mean_longitude=df3['longitude'].mean() 
df3['longitude'].fillna(value=mean_longitude,inplace=True) 
mean_review_scores_rating=df3['review_scores_rating'].mean() 
df3['review_scores_rating'].fillna(value=mean_review_scores_rating,inplace=True) 
mean_review_scores_accuracy=df3['review_scores_accuracy'].mean() 
df3['review_scores_accuracy'].fillna(value=mean_review_scores_accuracy,inplace=True) 
mean_review_scores_cleanliness=df3['review_scores_cleanliness'].mean() 
df3['review_scores_cleanliness'].fillna(value=mean_review_scores_cleanliness,inplace=True) 
mean_review_scores_checkin=df3['review_scores_checkin'].mean() 
df3['review_scores_checkin'].fillna(value=mean_review_scores_checkin,inplace=True) 
mean_review_scores_communication=df3['review_scores_communication'].mean() 
df3['review_scores_communication'].fillna(value=mean_review_scores_communication,inplace=True) 
mean_review_scores_location=df3['review_scores_location'].mean() 
df3['review_scores_location'].fillna(value=mean_review_scores_location,inplace=True) 
mean_review_scores_value=df3['review_scores_value'].mean() 
df3['review_scores_value'].fillna(value=mean_review_scores_value,inplace=True) 
mean_calculated_host_listings_count=df3['calculated_host_listings_count'].mean() 
df3['calculated_host_listings_count'].fillna(value=mean_calculated_host_listings_count,inplace=True) 
mean_calculated_host_listings_count_entire_homes=df3['calculated_host_listings_count_entire_homes'].mean() 
df3['calculated_host_listings_count_entire_homes'].fillna(value=mean_calculated_host_listings_count_entire_homes,inplace=True) 
mean_calculated_host_listings_count_private_rooms=df3['calculated_host_listings_count_private_rooms'].mean() 
df3['calculated_host_listings_count_private_rooms'].fillna(value=mean_calculated_host_listings_count_private_rooms,inplace=True) 
mean_calculated_host_listings_count_shared_rooms=df3['calculated_host_listings_count_shared_rooms'].mean() 
df3['calculated_host_listings_count_shared_rooms'].fillna(value=mean_calculated_host_listings_count_shared_rooms,inplace=True)

In [10]:
#Sustituimos los valores nulos de las columnas de tipo "Object"

df3["source"] =df3["source"].fillna("Desconocido") 
df3["name"] =df3["name"].fillna("Desconocido") 
df3["host_id"] =df3["host_id"].fillna("Desconocido") 
df3["host_response_time"] =df3["host_response_time"].fillna("Desconocido") 
df3["host_response_rate"] =df3["host_response_rate"].fillna("Desconocido") 
df3["host_acceptance_rate"] =df3["host_acceptance_rate"].fillna("Desconocido") 
df3["neighbourhood"] =df3["neighbourhood"].fillna("Desconocido") 
df3["neighbourhood_cleansed"] =df3["neighbourhood_cleansed"].fillna("Desconocido") 
df3["property_type"] =df3["property_type"].fillna("Desconocido") 
df3["room_type"] =df3["room_type"].fillna("Desconocido") 
df3["bathrooms_text"] =df3["bathrooms_text"].fillna("Desconocido") 
df3["Ame1"] =df3["Ame1"].fillna("Desconocido") 
df3["Ame2"] =df3["Ame2"].fillna("Desconocido") 
df3["Ame3"] =df3["Ame3"].fillna("Desconocido") 
df3["Ame4"] =df3["Ame4"].fillna("Desconocido") 
df3["Ame5"] =df3["Ame5"].fillna("Desconocido")

In [13]:
#Corroboramos que hemos eliminado los nulos de las columnas seleccionadas
df3.isnull().sum()

source                                           0
name                                             0
host_id                                          0
host_response_time                               0
host_response_rate                               0
host_acceptance_rate                             0
host_is_superhost                               14
host_listings_count                              0
host_total_listings_count                        0
host_identity_verified                          13
neighbourhood                                    0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms_text                                   0
bedrooms                                         0
beds                                             0
Ame1                                             0
Ame2                                             0
Ame3                                             0
Ame4                                             0
Ame5                                             0
price                                            0
minimum_nights                                   0
maximum_nights                                   0
number_of_reviews                                0
number_of_reviews_lastyear                       0
number_of_reviews_last30                         0
review_scores_rating                             0
review_scores_accuracy                           0
review_scores_cleanliness                        0
review_scores_checkin                            0
review_scores_communication                      0
review_scores_location                           0
review_scores_value                              0
instant_bookable                                 8
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
dtype: int64

In [14]:
df3.to_csv("RioClean.csv")

**Sustituci√≥n de Outliers**